---

- hosts: all
  become: true
  tasks:
          - name: install httpd and telnet package
            yum:
                    name:
                            - httpd
                            - telnet
                    state: latest
                    update_cache: yes
