---

- hosts: all
  become: true
  pre_tasks:
          - name: install updates (Red Hat)
            tags: always
            dnf:
                    update_only: yes
                    update_cache: yes

- hosts: primary_servers
  become: true
  tasks:
          - name: install httpd and telnet package
            tags: httpd,telnet
            yum:
                    name:
                            - httpd
                            - telnet
                    state: latest

          - name: copy default html file for site
            tags: httpd,file
            copy:
                    src: default_site.html
                    dest: /var/www/html/index.html
                    owner: root
                    group: root
                    mode: 0644

- hosts: secondary_servers
  become: true
  tasks:
          - name: install mariadb package (Red Hat)
            tags: mariadb,db
            dnf:
                    name: mariadb
                    state: latest

          - name: copy default html file for site
            tags: secondary,db
            copy:
                    src: default_site.html
                    dest: /var/www/html/index.html
                    owner: root
                    group: root
                    mode: 0644
                    
