---

- hosts: all
  become: true
  pre_tasks:
          - name: update repo cache (Red Hat)
            tags: always
            dnf:
                    update_cache: yes
            changed_when: false


- hosts: all
  become: true
  tasks: 

        
          - name: add ssh key for simone
            tags: always
            authorized_key:
                    user: simone
                    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILUfNm76u40NCsX+mUSnrAGOaNnpXX7nigW7pcor8EXa ansible"


- hosts: primary_servers
  become: true
  tasks:
          - name: install httpd and telnet package
            tags: httpd,telnet
            yum:
                    name:
                            - httpd
                            - telnet
                    state: latest


- hosts: secondary_servers
  become: true
  tasks:
          - name: install mariadb package (Red Hat)
            tags: mariadb,db
            dnf:
                    name: mariadb
                    state: latest

          - name: change e-mail address for admin
            tags: apache,redhat,httpd
            lineinfile:
                    path: /etc/httpd/conf/httpd.conf
                    regexp: '^ServerAdmin'
                    line: ServerAdmin somebody@example.com
            register: httpd

          - name: restart httpd (RedHat)
            tags: apache,redhat,httpd
            service:
                    name: httpd
                    state: restarted
            when: httpd.changed

          - name: copy default html file for site
            tags: secondary,db
            copy:
                    src: default_site.html
                    dest: /var/www/html/index.html
                    owner: root
                    group: root
                    mode: 0644
                    
          - name: install unzip
            package:
                    name: unzip

          - name: install terraform 
            unarchive:
                    src: terraform_1.7.0_linux_amd64.zip
                    dest: /usr/local/bin
                   # remote_src: yes
                    mode: 0755
                    owner: root
                    group: root

          - name: start httpd (RedHat)
            tags: httpd,apache,redhat
            service:
                    name: httpd
                    state: started

